### ISSUE TITLE
explain how NAIPs are indexed on the S3 bucket

### ISSUE THREAD

**Issue by andrewljohnson** [trailbehind/DeepOSM#33]
I don't understand how I can make an index of the NAIP bucket on S3. The parameters are as follows: ['md', '2013', '1m', 'rgbir', '38077']

I understand all the parameters but the last one... I assume that is some sort of grid or ordinal ID. 

If I knew what the final parameter was, I could write a script to get training data from any state/year. Now it's limited to a certain place in Maryland, around Washington DC.

**Comment by brunosan** [comment]
AFAIK this is the [FIPS code](https://en.wikipedia.org/wiki/FIPS_county_code), as stated on the [appendix [page 18] here](https://www.fsa.usda.gov/Internet/FSA_File/naip-to-3-14-1_amend1.pdf)...

**Comment by andrewljohnson** [comment]
Thanks @brunosan 👍

**Comment by brunosan** [comment]
Btw, I noticed that at the linked USDA page on the wiki article you can get plain text codes, but I couldn't find the matching example above.

**Comment by andrewljohnson** [comment]
The codes in the filenames were not matching up to FIPS as far as I could tell, so I was wondering what was up.

Maybe this is moot though. I think the NAIPs need to be downloaded to get exact geo information. I don't think even the FIPS code and other filename info could be mapped to a good bounds for each file.

I think I'll change the scripts to work with any given US state (plus year) for now... instead of trying to exactly geo-index the whole bucket. That should serve my needs for doing some geographically disparate analyses.
