### ISSUE TITLE
run tests automatically on pull requests

### ISSUE THREAD

**Issue by andrewljohnson** [trailbehind/DeepOSM#35]
Is Travis something free for FOSS projects?

Also, is it worth enforcing pep8 as a test on PRs?

**Comment by riordan** [comment]
Yes and yes

**Comment by zain** [comment]
Do we have any tests?

**Comment by zain** [comment]
Gave a shot at this ticket, but it looks like I need admin rights on this repo to do anything w/ travis.

**Comment by andrewljohnson** [comment]
FTFY, you're an admin now.

I thought our first test would be enforcing pep8 :)
