### ISSUE TITLE
Set up an Overpass server, use this instead of PBF munging

### ISSUE THREAD

**Issue by zain** [trailbehind/DeepOSM#39]
I'm going to spin up a `t2.small` EC2 instance, install Overpass, and load the `north-america-latest.osm.bz2` OSM extract from geofabrik.de into it.

**Comment by andrewljohnson** [comment]
It seems like a good production solution could be: 
1. this Overpass instance 
2. RDS instance with NAIP data, plus app to manage it?
3. Tensorflow analyzer
4. an app for deeposm.org (web app for OSM review/edit). 

Apps 1 & 2 provide an API to app 3, which publishes data to S3 for app 4 to imbibe into its own Django Postgres?

How do we orchestrate that in production I guess is a question too?

**Comment by andrewljohnson** [comment]
merging with other infrastructure issues
