### ISSUE TITLE
Additional trainning set

### ISSUE THREAD

**Issue by brunosan** [trailbehind/DeepOSM#4]
[NAIP](http://www.fsa.usda.gov/programs-and-services/aerial-photography/imagery-programs/naip-imagery/) offers free 1 meter resolution images for the whole CONUS. They are georectified .tiff files by state, but not on z/x/y.

Data is accessible as "requester pays" on `s3://aws-naip`.
- [ ] Is this an upgrade to the current training set? (NAIP also has NIR bands).
  - [ ] If so, I understand there should be a logic built to go from tiff to zxy. Or request access to NAIP layer to a provider which has done that. e.g. [mapbox](https://www.mapbox.com/blog/open-imagery-update-for-mapbox-satellite/)

**Comment by andrewljohnson** [comment]
I was talking with @JesseCrocker and he agreed NAIP's NIR band data is good for feature detection. I could see moving to a better data set pretty quick, the MQ data is old, crusty, and RGB.

It shouldn't be too hard to chop of that data to match the tiles, or get it all harmonious otherwise.

**Comment by andrewljohnson** [comment]
done
