### ISSUE TITLE
INSTALL ISSUES

### ISSUE THREAD

**Issue by Hjy20255** [trailbehind/DeepOSM#63]
hi~ 
I have installed a docker  but cd /DeepOSM-master  make dev  then  run  python bin/create_training_data.py  ,i have a error : File "bin/create_training_data.py", line 6, in <module>
    from src.training_data import download_and_serialize  ImportError: No module named src.training_data
can you give me  a detailed tutorial

**Comment by andrewljohnson** [comment]
- What operating system are you using?
- Can you please paste in all of your terminal input/output as a comment on this issue, starting with the initial clone of the repo, and cd into the directory?

**Comment by Hjy20255** [comment]
ubuntu16.04  first  i had install  tensorflow 
1. install a Docker Binary.
2.git DeepOSM CODE
3.cd DeepOSM   make dev   have some errors  
ConnectionError: HTTPSConnectionPool(host='storage.googleapis.com', port=443): Max retries exceeded with url: /tensorflow/linux/cpu/tensorflow-0.8.0-cp27-none-linux_x86_64.whl (Caused by <class 'socket.error'>: [Errno 101] Network is unreachable)
The command '/bin/sh -c pip install --ignore-installed -r /DeepOSM/requirements_cpu.txt' returned a non-zero code: 2
Makefile:16: recipe for target 'build' failed
4.when i run  "python bin/create_training_data.py"
File "create_training_data.py", line 6, in <module>
    from src.training_data import download_and_serialize
ImportError: No module named src.training_data

-----------------------i am sorry  ,I'm a green hand  please tell  me  details

**Comment by andrewljohnson** [comment]
@Hjy20255 
1. you shouldn't have to install tensorflow, docker does it as part of make dev
2. It looks like you got a network error when docker tried to download tensorflow, which caused make dev to fail. Check your internet connection.
3. It won't work to call python bin/create_training_data.py unless make dev works successfully and puts you inside the docker machine

**Comment by Hjy20255** [comment]
hi ~  
1. cd  DeepOSM   make dev 
 Removing intermediate container 05289652859f
Successfully built eb7605e08e33
docker run -v `pwd`:/DeepOSM \
               -w /DeepOSM \
               -e CPLUS_INCLUDE_PATH=/usr/include/gdal \
               -e C_INCLUDE_PATH=/usr/include/gdal \
               -e AWS_ACCESS_KEY_ID= \
               -e AWS_SECRET_ACCESS_KEY= \
               -it deeposm /bin/bash
2. root@d9ae443e09af:/DeepOSM# python bin/create_training_data.py
error:
Traceback (most recent call last):
  File "bin/create_training_data.py", line 89, in <module>
    main()
  File "bin/create_training_data.py", line 85, in main
    args.tile_overlap)
  File "/DeepOSM/src/training_data.py", line 388, in download_and_serialize
    naip_year).download_naips()
  File "/DeepOSM/src/naip_images.py", line 51, in download_naips
    create_cache_directories()
  File "/DeepOSM/src/config.py", line 31, in create_cache_directories
    shutil.rmtree(CACHE_PATH)
  File "/usrb/python2.7/shutil.py", line 239, in rmtree
    onerror(os.listdir, path, sys.exc_info())
  File "/usrb/python2.7/shutil.py", line 237, in rmtree
    names = os.listdir(path)
OSError: [Errno 2] No such file or directory: '/DeepOSM/data/generated/'
I can't download all source data. 
-----------------------i am sorry ,I'm a green hand.

**Comment by jiankang1991** [comment]
I also have the same problem `OSError: [Errno 2] No such file or directory: '/DeepOSM/data/generated/'`

Have you solved it?
