### ISSUE TITLE
I think there is errata in "false positives" words

### ISSUE THREAD

**Issue by antran89** [trailbehind/DeepOSM#65]
I think the word "false positive" in README file: 

> render, as JPEGs, "false positive" predictions in the OSM data - i.e. where OSM lists a road, but DeepOSM thinks there isn't one.

It is not correct usage. According to [wiki](https://en.wikipedia.org/wiki/False_positives_and_false_negatives), it should be false negative. I hope you do not mind if I have this issue. 
Best regards,

**Comment by andrewljohnson** [comment]
Hmmm.. I think this is correct nomenclature. It's saying the OSM data itself has a false positive... i.e. OSM says a road exists, and DeepOSM says that's false.

I would consider a false negative in the OSM data to be where OSM is missing a road where one should exist.
