### ISSUE TITLE
Deeposm.org UI: Add "Flag as fixed" control

### ISSUE THREAD

**Issue by CloCkWeRX** [trailbehind/DeepOSM#67]
#59 talks a bit about "The scripts to gather data, train, and upload findings should run on a cycle, not manually when I press a button".

A simple 'this has been fixed' control could easily flag things for reassessment, or at least tag the record as probably fixed / shift it to another list.

**Comment by andrewljohnson** [comment]
Hmm, I think I'll get the cron job working this week, so this won't be necessary. I'm loathe to add extra buttons to the UI unless I feel it's strongly needed. 

Also, a human verifying it's fixed on OSM takes some work, and I'd be afraid people would mix up whether it's flagged as wrong or fixed.
