### ISSUE TITLE
Fail to run train_neural_net.py

### ISSUE THREAD

**Issue by Hjy20255** [trailbehind/DeepOSM#70]
“For output, DeepOSM will produce some console logs, and then JPEGs of the ways, labels, and predictions overlaid on the tiff.”
i run train_neural_net.py successfully . but there no JPEGs of the ways, labels, and predictions overlaid on the tiff.

**Comment by andrewljohnson** [comment]
I fixed this in this commit: https://github.com/trailbehind/DeepOSM/commit/3362bfb5e92c1865b1c377748d0eb63ebce4feb4

I want to clean this up a bit before I merge it to master.

**Comment by andrewljohnson** [comment]
fixed by 3362bfb

**Comment by Hjy20255** [comment]
Thank  you!  I have resolved the problem.
